// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){



var Aa=this,Ba=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ca=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Da=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ea=function(a){if(null==a)return String(a);var b=Da.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Fa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},la=function(a){if(!a||"object"!=Ea(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Fa(a,"constructor")&&!Fa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Fa(a,b)},Ga=function(a,b){var c=b||("array"==Ea(a)?[]:{}),d;for(d in a)if(Fa(a,d)){var e=a[d];"array"==Ea(e)?("array"!=Ea(c[d])&&(c[d]=[]),c[d]=Ga(e,c[d])):la(e)?(la(c[d])||(c[d]={}),c[d]=Ga(e,c[d])):c[d]=e}return c};var pa=null,Ia=Math.random(),Ja=null,Ka=null,ya=!1,La={},Ma={},za={};var Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Xa,Ya,Za,S,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,nb,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Lb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,T,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,pd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,
ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe;
(function(){var a=function(a){return{toString:function(){return a}}};Na=a("");Oa=a("0");Pa="";Qa=a("");Ra=a("");Sa=a("");Ta=a("");Ua=a("");Va=a("");Xa=a("");Ya=a("");Za=a("2");S=a("3");$a=a("");ab=a("");bb=a("");
cb=a("");db=a("");eb=a("");fb=a("");gb=a("");hb=a("");ib=a("");jb=a("");kb=a("");lb=a("");nb=a("");pb=a("");qb=a("");rb=a("");
sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");yb=a("");zb=a("4");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");
Lb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("5");Vb=a("");Wb=a("");Xb=a("6");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");
cc=a("");dc=a("");ec=a("");fc=a("7");gc=a("");hc=a("8");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("9");qc=a("");rc=a("");
sc=a("");tc=a("");uc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("10");Fc=a("");Gc=a("16");Hc=a("17");Ic=a("");Jc=a("");
Kc=a("");T=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("11");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("12");ad=a("");bd=a("");
cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");pd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");
Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");
Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");
ie=a("14");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");
ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge="";He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("15");Ne=a("");Oe=a("");Pe=a("");
Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("")})();var Ye=function(){},M=function(a){return"function"==typeof a},Ze=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},$e=function(a){return"number"==Ea(a)&&!isNaN(a)},af=function(a){return/^[0-9]+$/.test(a)},bf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},cf=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},O=function(a){return Math.round(Number(a))||0},na=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},df=function(a){var b=[];if(Ze(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},L=function(){return new Date},ef=function(a,b){if(!$e(a)||!$e(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},ff=function(){this.prefix="gtm.";this.values={}};ff.prototype.set=function(a,b){this.values[this.prefix+a]=b};ff.prototype.get=function(a){return this.values[this.prefix+a]};ff.prototype.contains=function(a){return void 0!==this.get(a)};
var gf=function(a,b,c){try{if(!a[ed])return a[Ec](a,b||Ye,c||Ye);c&&c()}catch(d){}return!1},hf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=cf(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},jf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},kf=function(a){return function(){return a("GTM-WLGFZV")}},lf=function(a){for(var b=0;b<a.length;b++)a[b]()},mf=L().getTime(),ja=function(){return"gtm"+
mf++},ma=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},nf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},of=function(a){return null!==a&&void 0!==a&&void 0!==a.length},pf=function(a,b){0==b?a.Ra=!0:a.complete=!0;var c=a.g;a.o&&(a.o.Ea[c]=b);La[c]&&(La[c].state=b)},qf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var I=window,Q=document,tf=navigator,K=function(a,b,c){var d=I[a];I[a]=void 0===d||c?b:d;return I[a]},P=function(a,b,c,d){return(d||"http:"!=I.location.protocol?a:b)+c},uf=function(a){var b=Q.getElementsByTagName("script")[0]||Q.body||Q.head;b.parentNode.insertBefore(a,b)},oa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=Q.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;oa(d,b);c&&(d.onerror=c);uf(d)},fa=function(a,b){var c=Q.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";uf(c);oa(c,b);void 0!==a&&(c.src=a);return c},C=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},V=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},u=function(a){I.setTimeout(a,0)},ra=!1,
sa=[],vf=function(a){if(!ra){var b=Q.createEventObject,c="complete"==Q.readyState,d="interactive"==Q.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ra=!0;for(var e=0;e<sa.length;e++)sa[e]()}sa.push=function(){for(var a=0;a<arguments.length;a++)u(arguments[a]);return 0}}},wf=0,xf=function(){if(!ra&&140>wf){wf++;try{Q.documentElement.doScroll("left"),vf()}catch(a){I.setTimeout(xf,50)}}},Ff=function(a){var b=Q.getElementById(a);if(b&&Ef(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Ef(document.all[a][c],
"id")==a)return document.all[a][c];return b},Ef=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Gf=function(a){return a.target||a.srcElement||{}},wa=function(a){var b=Q.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Hf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},If=!1,Jf=[],Kf=function(){if(!If){If=!0;for(var a=0;a<Jf.length;a++)Jf[a]()}},Lf=function(a){a=a||I;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},ua=function(a){window.console&&window.console.log&&window.console.log(a)};var Mf=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||I.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||I.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:I.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=bf(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Nf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},xa=function(a){var b=Q.createElement("a");
a&&(b.href=a);return b};var ea=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Mf(xa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},ia=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var aa=function(a,b,c){r(a,b,c)},x=I,p=function(a,b,c){b&&(void 0===x[a]||c&&!x[a])&&(x[a]=b);return x[a]},ba=function(a,b,c){return("https:"==I.location.protocol?a:b)+c};var Of=new ff,Pf={},Rf={set:function(a,b){Ga(Qf(a,b),Pf)},get:function(a){return J(a,2)},reset:function(){Of=new ff;Pf={}}},J=function(a,b){if(2==b){for(var c=Pf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Of.get(a)},Qf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Sf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Tf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Uf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Vf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Wf=function(){var a=J("gtm.whitelist");
var b=a&&Vf(df(a),Tf),c=J("gtm.blacklist")||J("tagTypeBlacklist")||[];Sf.test(I.location&&I.location.hostname)&&(c=df(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Vf(df(c),Uf),e={};return function(f){var g=f&&f[Ec];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>bf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>bf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=bf(d,g.a)))a:{for(var n=g.b||[],q=new ff,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<n.length;t++)if(q.get(n[t])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var rf=function(a){var b=Q;return Xf?b.querySelectorAll(a):null},Yf=!1;if(Q.querySelectorAll)try{var Zf=Q.querySelectorAll(":root");Zf&&1==Zf.length&&Zf[0]==Q.documentElement&&(Yf=!0)}catch(a){}var Xf=Yf;var _eu=function(a){var b=String(J("gtm.elementUrl")||a[$b]||""),c=xa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ka};_e.a="e";_e.b=["google"];var dg=/(^|\.)doubleclick\.net$/i,eg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,fg=function(a){for(var b=String(Q.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=cf(e[0]);if(f&&f==a){var g=cf(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},gg=function(a,b,c,d,e){if(dg.test(Q.location.hostname)||"/"==c&&eg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=Q.cookie;Q.cookie=f;return g!=
Q.cookie||0<=bf(fg(a),b)},hg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},ig=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},jg=function(){var a=Mf(I.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var kg=function(a,b){this.f=a;this.i=b};kg.prototype.toString=function(){var a=""+this.f;1<this.i&&(a=a+"-"+this.i);return a};var lg=function(a,b){this.Ca=a;this.da=b};lg.prototype.toString=function(){return""+this.da+"."+this.Ca};var og=function(a,b){var c=new mg(null,a,b);ng(c);return c},mg=function(a,b,c){this.Ka=Math.floor(L().getTime()/864E5);this.ca=b||"auto";this.U=c||"/";var d=hg(this.ca),e=ig(this.U);this.C=a||new kg(d,e);this.h=[];this.A=new ff},qg=function(a,b,c){b&&(""==c.Ca?pg(a,b):(a.A.contains(b)||a.h.push(b),a.A.set(b,c)))},rg=function(a,b){for(var c=0;c<b.length;c++)qg(a,b[c][0],b[c][1])},pg=function(a,b){var c=bf(a.h,b);0<=c&&a.h.splice(c,1);a.A.set(b,void 0)},sg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.A.get(d)])}return b},tg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.A.get(a.h[c]).da);return 864E5*b};mg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.A.get(c).toString())}return"GAX1."+this.C.toString()+"."+a.join("!")};
var ug=function(a,b){for(var c=new Date,d=ig(a.U),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.A.get(g).da<a.Ka&&e.push(g)}for(f=0;f<e.length;f++)pg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(tg(a));if("auto"!=a.ca)return gg("_gaexp",a.toString(),a.U,a.ca,c);for(var h=jg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.C=new kg(hg(h[k]),d),gg("_gaexp",a.toString(),a.U,h[k],c)))return!0;return!1},ng=function(a){for(var b=a.C.f,c=a.C.i,d=fg("_gaexp"),e=[],f=0;f<d.length;f++){var g=vg(a,d[f]);g&&e.push(g)}qf(e,
function(a,d){var e=a.C,f=d.C;return e.f==f.f&&e.i==f.i?!1:e.f==b&&e.i==c?!0:f.f==b&&f.i==c?!1:e.f==b?f.f!=b||e.i<f.i:f.f==b?!1:e.i==c?f.f!=b&&(f.i!=c||e.f<f.f):f.i==c?!1:e.f<f.f||e.f==f.f&&e.i<f.i});a.C=0<e.length?e[0].C:new kg(b,c);for(f=e.length-1;0<=f;f--)rg(a,sg(e[f]))},vg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=cf(e[0]);if(0!=f.length){var g=2==e.length?cf(e[1]):"1";if(af(f)&&af(g)){d=new kg(O(f),O(g));
break a}}}d=void 0}if(d){for(var h=new mg(d,a.ca,a.U),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!af(l[1]))return;qg(h,l[0],new lg(l[2],O(l[1])))}}return h}}};var _f=function(a){var b=String(J("gtm.referrer")||Q.referrer);if(!b)return b;var c=xa(b);return b};_f.a="f";_f.b=["google"];var ha=function(a){var b=I.location,c;(c=a[Pb]?a[Pb]:J("gtm.url"))&&(b=xa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[zb]&&(f=Mf(b,a[zb],a[ce],a[Zb],a[Qd]));return f},_u=ha;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Za])==String(a[S])};_eq.a="eq";_eq.b=["google"];var Jg=Math.random(),Kg="1.000000">Jg;var Lg=Ye;var Mg=Ye,Ng=[],Og=!1,Pg=function(a){return I["dataLayer"].push(a)},Qg=function(a){var b=!1;return function(){!b&&M(a)&&u(kf(a));b=!0}},Wg=function(){for(var a=!1;!Og&&0<Ng.length;){Og=!0;var b=Ng.shift();if(M(b))try{b.call(Rf)}catch(ta){}else if(Ze(b))a:{var c=b;if("string"==Ea(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Pf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(ta){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,
n=k[m];Of.set(l,n);Ga(Qf(l,n),Pf)}var q=!1,t=k.event,v=void 0;if(t){v=mf++;Ka=t;if(!k["gtm.uniqueEventId"]){var w=v;Of.set("gtm.uniqueEventId",w);Ga(Qf("gtm.uniqueEventId",w),Pf)}var A=Qg(k.eventCallback),E=k.eventTimeout;E&&I.setTimeout(A,Number(E));q=Mg(v,t,A,k.eventReporter)}Ja||(Ja=k["gtm.start"])&&Lg();var F=k,D=v,y=t,G=Pf;if(!q){var B=v,H=t;
}Ka=null;a=q||a}var R=b,N=Pf;Vg();Og=!1}return!a},Xg=function(){var a=Wg();try{var b=I["dataLayer"].hide;if(b&&void 0!==b["GTM-WLGFZV"]&&b.end){b["GTM-WLGFZV"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var Yg,Zg,$g,ah=/(Firefox\D28\D)/g.test(tf.userAgent),gh=function(a,b){return function(c){c=c||I.event;var d=Gf(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Hf(d,["a","area"]),e=!d||!d.href||bh(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?$g:Zg;if(c.defaultPrevented||!1===c.returnValue||c.qa&&c.qa()){if(d){var g={simulateDefault:!1},h=ch(f,["wnc","nwnc"]);h&&dh(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=ch(f,
["wnc","nwnc","nwc","wc"]);(k=dh(a,d,g,f.wt,m))||(eh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ah;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=fh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},dh=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Ef(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=hh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=ih(b);g.eventTimeout=f;g.eventCallback=jh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Pg(g)},
ih=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},kh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},fh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(tf.userAgent),e=kh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=I.frames&&I.frames[f]||I[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+L().getTime(),b.targetWindow=I.open("",b.targetWindowName));break;default:d&&!I.frames[e]?(b.simulateDefault=!1,c=!0):(I.frames[e]||(b.targetWindowName=e),b.targetWindow=I.frames[e]||I.open("",e))}return c},hh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||L().getTime(),500>L().getTime()-c&&I.setTimeout(hh(a,b,c),25)))}},jh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);Q.gtmSubmitFormNow=!0;lh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||L().getTime(),500>L().getTime()-c&&I.setTimeout(jh(a,b,c),25)}},ch=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},mh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},eh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<nh.length;c++)if(a.passingRules[c]){var d=nh[c],e=oh[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},ph=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(Q.gtmHasClickListenerTag)return;Q.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Gf(a);b&&dh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Yg&&(Yg=Nf(Q.location));mh(Zg,b||!1,c||!1,d,e);if(Q.gtmHasLinkClickListenerTag)return;
Q.gtmHasLinkClickListenerTag=!0;f="click";g=gh(a,b||!1);break;case "FORM_SUBMIT":mh($g,b||!1,c||!1,d,e);if(Q.gtmHasFormSubmitListenerTag)return;Q.gtmHasFormSubmitListenerTag=!0;f="submit";g=gh(a,b||!1);break;default:return}V(Q,f,g,h)},bh=function(a){if(!Yg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=xa(a);return Yg==Nf(c)},lh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
Q.gtmFormElementSubmitter||(Q.gtmFormElementSubmitter=Q.createElement("form"));return Q.gtmFormElementSubmitter.submit.call?Q.gtmFormElementSubmitter.submit:a.submit};var wg=new String("undefined"),xh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===wg?b:a[d]);return c.join("")}};xh.prototype.toString=function(){return this.resolve("undefined")};xh.prototype.valueOf=xh.prototype.toString;var yh={},zh=function(a,b){var c=mf++;yh[c]=[a,b];return c},Ah=function(a){var b=a?0:1;return function(a){var d=yh[a];if(d&&M(d[b]))d[b]();yh[a]=void 0}};var Bh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ch=function(a,b){return a<b?-1:a>b?1:0};var Dh;a:{var Eh=Aa.navigator;if(Eh){var Fh=Eh.userAgent;if(Fh){Dh=Fh;break a}}Dh=""}var W=function(a){return-1!=Dh.indexOf(a)};var Gh=W("Opera"),Hh=W("Trident")||W("MSIE"),Ih=W("Edge"),Jh;if(Jh=W("Gecko"))Jh=!(-1!=Dh.toLowerCase().indexOf("webkit")&&!W("Edge"));var Kh=Jh&&!(W("Trident")||W("MSIE"))&&!W("Edge"),Lh=-1!=Dh.toLowerCase().indexOf("webkit")&&!W("Edge");Lh&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var Mh=Aa.navigator||null;Mh&&(Mh.appVersion||"").indexOf("X11");W("Android");!W("iPhone")||W("iPod")||W("iPad");W("iPad");W("iPod");
var Nh=function(){var a=Aa.document;return a?a.documentMode:void 0},Oh;a:{var Ph="",Qh=function(){var a=Dh;if(Kh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ih)return/Edge\/([\d\.]+)/.exec(a);if(Hh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Lh)return/WebKit\/(\S+)/.exec(a);if(Gh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Qh&&(Ph=Qh?Qh[1]:"");if(Hh){var Rh=Nh();if(null!=Rh&&Rh>parseFloat(Ph)){Oh=String(Rh);break a}}Oh=Ph}
var Sh=Oh,Th={},Uh=function(a){var b;if(!(b=Th[a])){for(var c=0,d=Bh(String(Sh)).split("."),e=Bh(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],q=l.exec(k)||["","",""];if(0==n[0].length&&0==q[0].length)break;c=Ch(0==n[1].length?0:parseInt(n[1],10),0==q[1].length?0:parseInt(q[1],10))||Ch(0==n[2].length,0==q[2].length)||Ch(n[2],q[2])}while(0==c)}b=Th[a]=0<=c}return b},
Vh=Aa.document,Wh=Vh&&Hh?Nh()||("CSS1Compat"==Vh.compatMode?parseInt(Sh,10):5):void 0;var Xh;if(!(Xh=!Kh&&!Hh)){var Yh;if(Yh=Hh)Yh=9<=Number(Wh);Xh=Yh}Xh||Kh&&Uh("1.9.1");Hh&&Uh("9");var Zh=function(a){Zh[" "](a);return a};Zh[" "]=function(){};var va=function(a,b){var c="";Hh&&!$h(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(ai)a.srcdoc=d;else if(bi){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else ci(a,d)},ai=Lh&&"srcdoc"in document.createElement("iframe"),bi=Kh||Lh||Hh&&Uh(11),ci=function(a,b){Hh&&Uh(7)&&!Uh(10)&&6>di()&&ei(b)&&(b=fi(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Hh&&!$h(a)?gi(a,c):c()},di=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},$h=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Zh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},hi=0,gi=function(a,b){var c="goog_rendering_callback"+hi++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},ei=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},fi=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var xi=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=ui(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=vi(a+"{"+e+"}",f);wi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},yi=null,ui=function(a){if(yi)return yi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return yi=c}0==a.styleSheets.length&&
a.createStyleSheet();return yi=a.styleSheets[0]},vi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},wi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Fi={},Gi=void 0,Hi=function(a){var b=Fi[a];b||(b={id:a,s:[],R:0,Fa:null,wa:void 0,Aa:!1},Fi[a]=b);Gi=b},Ji=function(a,b,c,d){var e=Gi;if(!Xf||!e)return!1;var f={id:e.id+":"+e.s.length,Za:b,O:[],Ua:c,D:a,oa:0,ma:d||null,Ja:0,P:!1};e.s.push(f);null===a?(f.P=!0,b(null)):Ii(e);return!0},Ki=function(a){var b=xi(a,"visibility","hidden",!0);return function(){M(b)&&b.apply();b=null}},Li=function(a,b,c,d){var e=b;if(!ra){var f=Ki(a.v);sa.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Ji(a,e,
c,d)},Ii=function(a){if(!a.Aa){for(var b=a.R;b<a.s.length;b++){var c=a.s[b],d=b==a.R;if(!c.P&&!Mi(d,c))break;c.P&&d&&a.R++}a.s.length>a.R?(a.Fa||(a.Fa=I.setTimeout(function(){a.Fa=null;Ii(a)},80)),ra||a.wa||(a.wa=function(){u(function(){Ii(a)})},V(Q,"DOMContentLoaded",a.wa))):Ni(a)}},Ni=function(a){for(var b=0;b<a.s.length;b++){var c=a.s[b];if(c.D)for(var d=rf(c.D.v)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Oi(f,c.id),c.O.push(Pi(f,c.id)))}}},Mi=
function(a,b){var c=[];if(b.D){var d=Qi(b.D,b.id),e=null;b.ma&&(e=Qi(b.ma,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ra&&(null===b.ma.m||b.Ja+c.length<b.ma.m)))break;c.push({element:g,zb:h})}}if(!ra&&b.Ua&&(!a||null==b.D.m||b.D.m!=b.oa+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].zb,n;b.oa++;Oi(m,b.id);l&&(b.Ja++,n=b.id+"-t",Oi(l,n));var q=b.Za(m,l);M(q)&&b.O.push(q);b.O.push(Pi(m,b.id));l&&n&&b.O.push(Pi(l,n))}if(b.D.m&&
b.D.m==b.oa||ra)b.P=!0;return!0},Oi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Pi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Qi=function(a,b){for(var c=rf(a.v)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.B&&!Ri(f))break;d.push(f)}}return d},Ri=function(a){if(ra)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ui,Vi;var ej=function(a){return function(){}},fj=function(a){return function(){}};var Ij=function(a){var b=I||Aa,c=b.onerror,d=!1;Lh&&!Uh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,sb:g,Pb:h,error:k});return d}};var ek=26,fk=[],gk=[],hk=[],ik=new ff,jk=[],Z=[],nh=[],oh=[],kk=function(){this.G=[]};kk.prototype.set=function(a,b){this.G.push([a,b]);return this};kk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.G.length;d++){var e=lk(this.G[d][0],a,b),f=lk(this.G[d][1],a,b);c[e]=f}return c};var mk=function(a){this.index=a};mk.prototype.resolve=function(a,b){var c=hk[this.index];if(c&&!b(c)){var d=c[Pc];if(a){if(a.get(d))return;a.set(d,!0)}c=lk(c,a,b);a&&a.set(d,!1);return gf(c)}};
var _M=function(a){return new mk(a)},nk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=lk(fk[a[f]],b,c);g===wg&&(e=!0);d.push(g)}return e?new xh(d):d.join("")}},_T=function(a){return new nk(arguments)},ok=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=lk(a[0],c,d);if(a[0]instanceof mk&&b(8)&&b(16)){if(e===wg)return e;var f=ja();ik.set(f,e);return'google_tag_manager["GTM-WLGFZV"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new ok(arguments)},pk=function(a,b){this.u=a;this.la=b},_R=function(a,b){return new pk(a,b)},qk=function(a,b){return lk(a,new ff,b)},lk=function(a,b,c){var d=a;if(a instanceof mk||a instanceof kk||a instanceof nk||a instanceof ok)return a.resolve(b,
c);if(!(a instanceof pk))if(Ze(a))for(var d=[],e=0;e<a.length;e++)d[e]=lk(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=lk(a[f],b,c))}return d},rk=function(a,b){var c=b[a],d=c;if(c instanceof mk||c instanceof ok||c instanceof nk||c instanceof pk)d=c;else if(Ze(c))for(var d=[],e=0;e<c.length;e++)d[e]=rk(c[e],b);else if("object"==typeof c){var d=new kk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],rk(c[f],b))}return d},tk=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=fk[e[1]]);if(1==a)for(var f=sk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=gk[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=sk(e[g]);3==a&&(c[d]=fk[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=fk[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},sk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<ek;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},uk=function(a,b,c){a.push.apply(a,tk(b,c))};
var Sg=function(){},Ck=function(a){},Vg=function(){},Dk=function(a){},Ek=function(a,b){},Fk=function(a,b){},Tg=function(a){};var Gk=function(a){var b=this;this.g=a;this.complete=this.Ra=!1;this.ka=[];this.ea=[];this.M=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||lf(b.ka);pf(b,1);if(Ma[a])for(var e=0;e<Ma[a].length;e++)Ma[a].shift().M()};this.L=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||
lf(b.ea);pf(b,2);if(Ma[a])for(var e=0;e<Ma[a].length;e++)Ma[a].shift().L()};this.w=Ye},Hk=function(a,b){a.ka.push(b)},Ik=function(a,b){a.ea.push(b)},Jk=function(a){this.H=[];this.Da=[];this.La={};this.ua=[];this.S=0;this.Pa={};this.Sa={};this.Ea={};this.event=a};Jk.prototype.addListener=function(a){this.ua.push(a)};
var Kk=function(a,b,c,d,e,f){if(!c.complete){a.H[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Ze(d)?d.slice():["or",d];e=Ze(e)?e.slice():[e];f=Ze(f)?f.slice():[f];a.La[b]=d;a.Pa[b]=0<e.length;a.Sa[b]=0<f.length;a.S++;var g=function(){0<a.S&&a.S--;0<a.S||lf(a.ua)};Hk(c,g);Ik(c,g)}},Lk=function(a,b,c){a.H[b]&&(Hk(a.H[b],function(){c(b,!0)}),Ik(a.H[b],function(){c(b,!1)}))},Mk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof pk&&a[g].u===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Qk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Nk(h,b,a);if(f=g){var k=Ok(b,!0);0<k.length&&e(k[0].u);c.push(f);var l=Ok(b,!1);0<l.length&&e(l[0].u)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Ok(g.g,!0);if(0<h.length){var k=c[f-1],m=Pk(g);Hk(k,m);0==h[0].la&&Ik(k,m)}var l=Ok(g.g,!1);0<l.length&&(m=Pk(c[f+1]),Hk(g,m),0==l[0].la&&Ik(g,m))}a.Da.push(c)}},Ok=function(a,b){var c=b?$d:qe,d=Z[a],e=void 0===d[c]?[]:d[c];return Ze(e)?e:[e]},Pk=function(a){return function(){a.w()}},Sk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Ok(a,!0);0<b.length&&f(b[0].u);e.push(a);var c=Ok(a,!1);0<c.length&&f(c[0].u)};
f(d.g);b[d.g]=e}Rk(a,b);return b},Rk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<bf(b[e],d)){delete b[d];break}}};var Uk=function(a,b){return function(){a[Gc]=b.M;a[Hc]=b.L;var c=b.g,d=b.o&&b.o.Ea[c],e=La[c]&&La[c].state,f=d?void 0!==d:b.Ra||b.Qb,g=La[c]&&La[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){pf(b,0);var m=b.o?b.o.event:void 0;a=Tk(a,m?m.c:Wf());if(m){var l=a;Ek(m,c)}gf(a,b.M,b.L)}else h&&0==e||k&&0==d?Ma[c].push(b):h&&1==e||k&&1==d?b.M():b.L()}},Tk=function(a,b){a=qk(a,b);return a},Nk=function(a,b,c){var d=new Gk(b);d.o=c;Hk(d,ej(a));Ik(d,fj(a));d.w=Uk(a,d);return d};
var Yk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];I[m()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!la(b))return!1;for(var e=ma(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[hc]?c=J("ecommerce"):
a[gc]&&(c=a[gc].ecommerce);if(!la(c))return;c=Object(c);var e=ma(a[Bc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=w[e]?na(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}K("GoogleAnalyticsObject",a[kd]||"ga",!1);var m=function(){return I.GoogleAnalyticsObject},l=K(m(),function(){var a=I[m()];a.q=a.q||[];a.q.push(arguments)},!1);l.l=Number(L());var n="",q="";"string"!=typeof a[De]?(q=ja(),n=q+"."):""!==
a[De]&&(q=a[De],n=q+".");var t=!1;
var A={name:q};l("create",a[Oa],A);d("set","&gtm","GTM-WLGFZV");var F;a[$c]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(M(a[Ic]))a[Ic]();else{var c=a[Bc],d=c&&c.hitCallback;M(d)&&d()}b()});if(a[ze]){}else if(a[Ae]){}else if(a[Ce]){}else if(a[Be]){}else if(a[Yb]){}else if(a[Wb]){}else if(a[ye]){}else{a[pc]&&(d("require","ec","ec.js"),h());if(a[fc]&&!a[rc]){var N="_dc_gtm_"+String(a[Oa]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:N})}F?d("send","pageview",F):d("send","pageview");}if(!Yk){var U=a[Ub]?"u/analytics_debug.js":"analytics.js";a[Qc]&&!a[Ub]&&(U="internal/"+U);
Yk=!0;r(P("https:","http:","//www.google-analytics.com/"+U,t),function(){I[m()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Zk,$k;var il=!1;var jl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=jk[b]&&qk(jk[b],c),e=d;if(d)if(d[Ya]&&Ze(d[S]))for(var f=d[S],e=!1,g=0;!e&&g<f.length;g++)d[S]=f[g],e=gf(d);else e=gf(d);a[b]=[e,d]}return a[b]}},Bk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.K(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.K(e[d],a.c)[0])return!1;return!0},kl=!1,Mg=function(a,b,c,d){switch(b){case "gtm.js":if(kl)return!1;kl=!0;break;case "gtm.sync":if(J("gtm.snippet")!=Ia)return!1}J("tagTypeBlacklist");
for(var e={id:a,name:b,aa:c||Ye,Z:sk(),ja:sk(),K:jl(),c:Wf()},f=[],g=0;g<nh.length;g++)if(Bk(e,nh[g])){f[g]=!0;for(var h=e,k=nh[g],m=k[1],l=0;l<m.length;l++)h.Z[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ja[n[l]]=!0}else f[g]=!1;Ek(e);var t=[];for(var v=0;v<ek;v++)if(e.Z[v]&&!e.ja[v])if(e.c(Z[v])){}else{t[v]=Z[v];}e.N=t;for(var w=new Jk(e),A=0;A<ek;A++)if(e.Z[A]&&!e.ja[A])if(e.c(Z[A])){}else{var E=e.N[A],F=Nk(E,A,w);Kk(w,A,F,E[ac],E[$d],E[qe]);if(E[Na])break}w.addListener(e.aa);for(var D=[],y=
0;y<w.H.length;y++){var G=w.H[y];if(G){var z=w.La[y],B=w.Pa[y],H=w.Sa[y];if(0!=z.length||B||H){if(0<z.length)for(var R=Mk(z,G.w),N=0;N<z.length;N++)z[N]instanceof pk&&z[N].u!=y&&Lk(w,z[N].u,R);(B||H)&&Qk(w,y)}else D.push(y)}}for(y=0;y<D.length;y++)w.H[D[y]].w();for(y=0;y<w.Da.length;y++){for(var ta=w.Da[y],U=ta,ga=[],da=0;da<U.length;da++){var ob=U[da],mb=ob.g,Mb=La[mb],qd=Mb.firingOption;0!=qd&&(1==qd&&void 0!==ob.o.Ea[mb]||2==qd&&void 0!==Mb.state)&&ga.push(ob)}var rd=Sk(ga),vc=void 0;for(vc in rd)if(rd.hasOwnProperty(vc)){for(var yf=
void 0,nj=void 0,nd=rd[vc],xl=nd[0],uj=nd[nd.length-1],vj,Ha=0;Ha<U.length;Ha++){var od=U[Ha];!yf&&od.g==xl&&0<Ha&&(yf=U[Ha-1]);od.g==uj&&Ha<U.length-1&&(nj=U[Ha+1]);if(-1<bf(nd,od.g))if(vj=U.splice(Ha,1)[0],od.g==uj)break;else Ha--}if(vj){var wj=Number(vc),ka=yf,zf=nj;if(ka){var yl=ka.ka[0],zl=ka.ea[0],xj=ka;xj.ka=[];xj.ea=[];Hk(ka,yl);Ik(ka,zl)}if(ka&&zf){var Af=Pk(zf);Hk(ka,Af);var Bf=Ok(ka.g,!1);0<Bf.length&&Bf[0].u!=wj&&0==Bf[0].la&&Ik(ka,Af);var Cf=Ok(zf.g,!0);0<Cf.length&&Cf[0].u!=wj&&0==Cf[0].la&&
Ik(ka,Af)}}}0<ta.length&&ta[0].w()}0<w.S||lf(w.ua);d&&M(d)&&d({passingRules:f,resolvedTags:e.N});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Aj in e.N)if(e.N.hasOwnProperty(Aj)){var Bj=e.N[Aj],Df;if(!(Df=void 0==Bj[Pc])){var Cj=Bj[Pc];Df=!("function"!=typeof String.prototype.startsWith?0===Cj.indexOf("_implicit"):Cj.startsWith("_implicit"))}if(Df)return!0}return!1};var ll={macro:function(a){if(ik.contains(a))return ik.get(a)}};ll.dataLayer=Rf;ll.onHtmlSuccess=Ah(!0);ll.onHtmlFailure=Ah(!1);ll.callback=function(a){za.hasOwnProperty(a)&&M(za[a])&&za[a]();delete za[a]};ll.cb=function(){var a=I.google_tag_manager;a||(a=I.google_tag_manager={});a["GTM-WLGFZV"]||(a["GTM-WLGFZV"]=ll);pa=a};(function(){var a=function(a){var c=K("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Zg=a("linkClickMap");$g=a("formSubmitMap")})();
fk.push.apply(fk,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','2275454_2147479553',_ua,true,'UA-6096819-11',false,'\x26tid',{10:8},1,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=rk(c,a);return b}());uk(gk,0,"10:0,10:1,11:2,2:3,3:4,10:6,13:7,0:8,9:9,8:9,15:9,5:9,6:9,1:11,12:9,7:9,14:12,10:13,11:14,11:15,4:16,11:17,4:18,10:19,11:20,11:21");uk(hk,1,"G,AAgB,AAgG,AAgY,AAAgB,CAAAC");uk(jk,1,"Z");uk(Z,1,"g_f");uk(nh,2,"B:B::");uk(oh,4,"5:");for(var ml=0;ml<Z.length;ml++){var nl=Z[ml],ol=1;nl[vd]?ol=2:nl[Je]&&(ol=0);La[ml]={firingOption:ol,state:void 0};Ma[ml]=[]}ll.cb();
(function(a){})("async");
(function(){var a=K("dataLayer",[],!1),b=K("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};sa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Jf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ng.push.apply(Ng,b);300<this.length;)this.shift();return Wg()};Ng.push.apply(Ng,a.slice(0));u(Xg)})();
if("interactive"==Q.readyState&&!Q.createEventObject||"complete"==Q.readyState)vf();else{V(Q,"DOMContentLoaded",vf);V(Q,"readystatechange",vf);if(Q.createEventObject&&Q.documentElement.doScroll){var wl=!0;try{wl=!I.frameElement}catch(a){}wl&&xf()}V(I,"load",vf)}"complete"===Q.readyState?Kf():V(I,"load",Kf);
(function(a){})("async");(function(){})();var _vs="res_ts:1464731784677000,srv_cl:127446390,ds:live,cv:1";
})()
